### ISSUE TITLE
Execution of Webcontroller error

### ISSUE THREAD

**Issue by 007scorpio** [mwrlabs/C3#1]
the system cannot find the specified path.
No executable found matching command "dotnet-C3WebController.dll"

**Comment by pawelkurowski** [comment]
Have you used "StartWebController.cmd" from source directory? You need to create build from source and then use script in build directory e.g. https://github.com/mwrlabs/C3/releases/download/1.0.0/C3-1.0.0.zip . Bare in mind that you need .Net Core (https://dotnet.microsoft.com/download)  to use WebController. Runtime will allow you to use compiled dll file, SDK allows to publish dll from source.

**Comment by 007scorpio** [comment]
Gateway |Debug> caught an exception while parsing Action. Throwing exception: unable to create channel

**Comment by 007scorpio** [comment]
Hello trust you are doing good. To have the ability for the gateway to connect to me, I need to have the IP on my public IP in aws. Yet it fails because the app binds to my private IP. How do I resolve this?

Thank you
