### ISSUE TITLE
Compiling 

### ISSUE THREAD

**Issue by 007scorpio** [mwrlabs/C3#2]
Can the program be compiled using vs 15?

**Comment by pawelkurowski** [comment]
It was never tested under VS15. It will probably not compile without code changes. C3 is c++17 project, so support of the standard in VS15 is only experimental.

**Comment by 007scorpio** [comment]
Hi 
Just asking as am still playing with the c3 tool. Sometimes communication stops after getting access to target on cobalt strike. Could it be my slack channel token?

Thanks

**Comment by pawelkurowski** [comment]
Hi,
This is probably not slack token issue. Bot associated to token can get blocked by rate limiting if you use token in too many relays, but I'm assuming this is not the case. Is this a problem where whole communication stops with Relay, or only communication with staged beacon? It could be that some action of beacon triggered detection and Relay was stooped, or relay still works, but beacon does not respond. It could be even

**Comment by 007scorpio** [comment]
I think the communication with stage beacon stops. Or if it the case for what you have listed above what will be the solution then? 

Thank you

**Comment by pawelkurowski** [comment]
In case of the rate limit, try to avoid too many channels using same token, or communicating from same host. You can change update delay to reduce usage of limit.

If it is only beacon that is not responsive, stage new one on same relay. This could be problem of CS external C2 itself, or MWR C3 issue. In both cases we will try to find the reason of it.

P.S. For beacons staged in the same process, you need to close tab associated with one of them, to open other tab. GUI will not allow you to open two 127.0.0.1:1234 tabs, even though CS differentiate them.
