### ISSUE TITLE
deletion of a gateway

### ISSUE THREAD

**Issue by 007scorpio** [mwrlabs/C3#3]
Is there an option to delete a gateway ?

**Comment by 007scorpio** [comment]
Ok Got it. Just Restart. :) Am getting acquainted with the tool so forgive me for some dump questions

**Comment by invictus-0x90** [comment]
you can send a gateway the "Close" command from the command centre. Also note that should the gateway terminate, you can restart it and it will reload the network it had previously. So should you accidentally close a gateway all is not lost.
